name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: default
          bundler-cache: true

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: Run tests
        run: |
          bundle exec rspec

# Uncomment to run system tests in CI
#          bin/rails test:system